///////////////////////////////////////////////////////////////////////////////
//
// This file was automatically generated by RANOREX.
// DO NOT MODIFY THIS FILE! It is regenerated by the designer.
// All your modifications will be lost!
// http://www.ranorex.com
//
///////////////////////////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.Drawing;
using Ranorex;
using Ranorex.Core;
using Ranorex.Core.Repository;
using Ranorex.Core.Testing;

namespace BSS_Demo
{
#pragma warning disable 0436 //(CS0436) The type 'type' in 'assembly' conflicts with the imported type 'type2' in 'assembly'. Using the type defined in 'assembly'.
    /// <summary>
    /// The class representing the BSS_DemoRepository element repository.
    /// </summary>
    [System.CodeDom.Compiler.GeneratedCode("Ranorex", global::Ranorex.Core.Constants.CodeGenVersion)]
    [RepositoryFolder("acc7ca1f-fcef-43df-a162-19deedd2f852")]
    public partial class BSS_DemoRepository : RepoGenBaseFolder
    {
        static BSS_DemoRepository instance = new BSS_DemoRepository();
        BSS_DemoRepositoryFolders.FormVipApplicationAppFolder _formvipapplication;

        /// <summary>
        /// Gets the singleton class instance representing the BSS_DemoRepository element repository.
        /// </summary>
        [RepositoryFolder("acc7ca1f-fcef-43df-a162-19deedd2f852")]
        public static BSS_DemoRepository Instance
        {
            get { return instance; }
        }

        /// <summary>
        /// Repository class constructor.
        /// </summary>
        public BSS_DemoRepository() 
            : base("BSS_DemoRepository", "/", null, 0, false, "acc7ca1f-fcef-43df-a162-19deedd2f852", ".\\RepositoryImages\\BSS_DemoRepositoryacc7ca1f.rximgres")
        {
            _formvipapplication = new BSS_DemoRepositoryFolders.FormVipApplicationAppFolder(this);
        }

#region Variables

#endregion

        /// <summary>
        /// The Self item info.
        /// </summary>
        [RepositoryItemInfo("acc7ca1f-fcef-43df-a162-19deedd2f852")]
        public virtual RepoItemInfo SelfInfo
        {
            get
            {
                return _selfInfo;
            }
        }

        /// <summary>
        /// The FormVipApplication folder.
        /// </summary>
        [RepositoryFolder("01568f3b-6108-48f0-b5fb-5f31f0c5a207")]
        public virtual BSS_DemoRepositoryFolders.FormVipApplicationAppFolder FormVipApplication
        {
            get { return _formvipapplication; }
        }
    }

    /// <summary>
    /// Inner folder classes.
    /// </summary>
    [System.CodeDom.Compiler.GeneratedCode("Ranorex", global::Ranorex.Core.Constants.CodeGenVersion)]
    public partial class BSS_DemoRepositoryFolders
    {
        /// <summary>
        /// The FormVipApplicationAppFolder folder.
        /// </summary>
        [RepositoryFolder("01568f3b-6108-48f0-b5fb-5f31f0c5a207")]
        public partial class FormVipApplicationAppFolder : RepoGenBaseFolder
        {
            RepoItemInfo _firstnameInfo;
            RepoItemInfo _lastnameInfo;
            RepoItemInfo _movieInfo;
            RepoItemInfo _musicInfo;
            RepoItemInfo _btclearInfo;
            RepoItemInfo _btaddInfo;
            RepoItemInfo _rbmaleInfo;
            RepoItemInfo _vipcount1Info;
            RepoItemInfo _vipcount0Info;
            RepoItemInfo _vipdatabaseInfo;

            /// <summary>
            /// Creates a new FormVipApplication  folder.
            /// </summary>
            public FormVipApplicationAppFolder(RepoGenBaseFolder parentFolder) :
                    base("FormVipApplication", "/form[@controlname='formVipApplication']", parentFolder, 30000, null, true, "01568f3b-6108-48f0-b5fb-5f31f0c5a207", "")
            {
                _firstnameInfo = new RepoItemInfo(this, "FirstName", "?/?/text[@accessiblename='First Name:']", 30000, null, "3d5c9225-ef98-4b65-9da6-4f88a8c08f18");
                _lastnameInfo = new RepoItemInfo(this, "LastName", "?/?/text[@accessiblename='Last Name:']", 30000, null, "d5cb5d38-ac52-4180-a401-7e04d9fbddba");
                _movieInfo = new RepoItemInfo(this, "Movie", ".//listitem[@accessiblename='Movie']", 30000, null, "22149078-53e0-48e8-93a4-86ddd17f9ba5");
                _musicInfo = new RepoItemInfo(this, "Music", ".//listitem[@accessiblename='Music']", 30000, null, "39113857-9aa5-43ef-ace8-acb1c205dc3b");
                _btclearInfo = new RepoItemInfo(this, "BtClear", "button[@controlname='btClear']", 30000, null, "61511833-eb3a-4b55-ac52-f10dbe282cc7");
                _btaddInfo = new RepoItemInfo(this, "BtAdd", "button[@controlname='btAdd']", 30000, null, "73ac2303-a2d0-4472-94ad-f6c33d4647b8");
                _rbmaleInfo = new RepoItemInfo(this, "RbMale", "?/?/radiobutton[@controlname='rbMale']", 30000, null, "b605e9d5-a7c0-4c6f-8cf5-f4e835d94bdf");
                _vipcount1Info = new RepoItemInfo(this, "VIPCount1", "?/?/text[@accessiblename='VIP count: 1']", 30000, null, "36baad25-2c68-4127-9c5a-b6b4c201cf90");
                _vipcount0Info = new RepoItemInfo(this, "VIPCount0", "?/?/text[@accessiblename='VIP count: 0']", 30000, null, "0949d5cc-0326-4e1f-9cf7-1a5590cae2dc");
                _vipdatabaseInfo = new RepoItemInfo(this, "VIPDatabase", "titlebar[@accessiblerole='TitleBar']", 30000, null, "c4e0c7f1-91ec-4b46-8fdd-a59558719532");
            }

            /// <summary>
            /// The Self item.
            /// </summary>
            [RepositoryItem("01568f3b-6108-48f0-b5fb-5f31f0c5a207")]
            public virtual Ranorex.Form Self
            {
                get
                {
                    return _selfInfo.CreateAdapter<Ranorex.Form>(true);
                }
            }

            /// <summary>
            /// The Self item info.
            /// </summary>
            [RepositoryItemInfo("01568f3b-6108-48f0-b5fb-5f31f0c5a207")]
            public virtual RepoItemInfo SelfInfo
            {
                get
                {
                    return _selfInfo;
                }
            }

            /// <summary>
            /// The FirstName item.
            /// </summary>
            [RepositoryItem("3d5c9225-ef98-4b65-9da6-4f88a8c08f18")]
            public virtual Ranorex.Text FirstName
            {
                get
                {
                    return _firstnameInfo.CreateAdapter<Ranorex.Text>(true);
                }
            }

            /// <summary>
            /// The FirstName item info.
            /// </summary>
            [RepositoryItemInfo("3d5c9225-ef98-4b65-9da6-4f88a8c08f18")]
            public virtual RepoItemInfo FirstNameInfo
            {
                get
                {
                    return _firstnameInfo;
                }
            }

            /// <summary>
            /// The LastName item.
            /// </summary>
            [RepositoryItem("d5cb5d38-ac52-4180-a401-7e04d9fbddba")]
            public virtual Ranorex.Text LastName
            {
                get
                {
                    return _lastnameInfo.CreateAdapter<Ranorex.Text>(true);
                }
            }

            /// <summary>
            /// The LastName item info.
            /// </summary>
            [RepositoryItemInfo("d5cb5d38-ac52-4180-a401-7e04d9fbddba")]
            public virtual RepoItemInfo LastNameInfo
            {
                get
                {
                    return _lastnameInfo;
                }
            }

            /// <summary>
            /// The Movie item.
            /// </summary>
            [RepositoryItem("22149078-53e0-48e8-93a4-86ddd17f9ba5")]
            public virtual Ranorex.ListItem Movie
            {
                get
                {
                    return _movieInfo.CreateAdapter<Ranorex.ListItem>(true);
                }
            }

            /// <summary>
            /// The Movie item info.
            /// </summary>
            [RepositoryItemInfo("22149078-53e0-48e8-93a4-86ddd17f9ba5")]
            public virtual RepoItemInfo MovieInfo
            {
                get
                {
                    return _movieInfo;
                }
            }

            /// <summary>
            /// The Music item.
            /// </summary>
            [RepositoryItem("39113857-9aa5-43ef-ace8-acb1c205dc3b")]
            public virtual Ranorex.ListItem Music
            {
                get
                {
                    return _musicInfo.CreateAdapter<Ranorex.ListItem>(true);
                }
            }

            /// <summary>
            /// The Music item info.
            /// </summary>
            [RepositoryItemInfo("39113857-9aa5-43ef-ace8-acb1c205dc3b")]
            public virtual RepoItemInfo MusicInfo
            {
                get
                {
                    return _musicInfo;
                }
            }

            /// <summary>
            /// The BtClear item.
            /// </summary>
            [RepositoryItem("61511833-eb3a-4b55-ac52-f10dbe282cc7")]
            public virtual Ranorex.Button BtClear
            {
                get
                {
                    return _btclearInfo.CreateAdapter<Ranorex.Button>(true);
                }
            }

            /// <summary>
            /// The BtClear item info.
            /// </summary>
            [RepositoryItemInfo("61511833-eb3a-4b55-ac52-f10dbe282cc7")]
            public virtual RepoItemInfo BtClearInfo
            {
                get
                {
                    return _btclearInfo;
                }
            }

            /// <summary>
            /// The BtAdd item.
            /// </summary>
            [RepositoryItem("73ac2303-a2d0-4472-94ad-f6c33d4647b8")]
            public virtual Ranorex.Button BtAdd
            {
                get
                {
                    return _btaddInfo.CreateAdapter<Ranorex.Button>(true);
                }
            }

            /// <summary>
            /// The BtAdd item info.
            /// </summary>
            [RepositoryItemInfo("73ac2303-a2d0-4472-94ad-f6c33d4647b8")]
            public virtual RepoItemInfo BtAddInfo
            {
                get
                {
                    return _btaddInfo;
                }
            }

            /// <summary>
            /// The RbMale item.
            /// </summary>
            [RepositoryItem("b605e9d5-a7c0-4c6f-8cf5-f4e835d94bdf")]
            public virtual Ranorex.RadioButton RbMale
            {
                get
                {
                    return _rbmaleInfo.CreateAdapter<Ranorex.RadioButton>(true);
                }
            }

            /// <summary>
            /// The RbMale item info.
            /// </summary>
            [RepositoryItemInfo("b605e9d5-a7c0-4c6f-8cf5-f4e835d94bdf")]
            public virtual RepoItemInfo RbMaleInfo
            {
                get
                {
                    return _rbmaleInfo;
                }
            }

            /// <summary>
            /// The VIPCount1 item.
            /// </summary>
            [RepositoryItem("36baad25-2c68-4127-9c5a-b6b4c201cf90")]
            public virtual Ranorex.Text VIPCount1
            {
                get
                {
                    return _vipcount1Info.CreateAdapter<Ranorex.Text>(true);
                }
            }

            /// <summary>
            /// The VIPCount1 item info.
            /// </summary>
            [RepositoryItemInfo("36baad25-2c68-4127-9c5a-b6b4c201cf90")]
            public virtual RepoItemInfo VIPCount1Info
            {
                get
                {
                    return _vipcount1Info;
                }
            }

            /// <summary>
            /// The VIPCount0 item.
            /// </summary>
            [RepositoryItem("0949d5cc-0326-4e1f-9cf7-1a5590cae2dc")]
            public virtual Ranorex.Text VIPCount0
            {
                get
                {
                    return _vipcount0Info.CreateAdapter<Ranorex.Text>(true);
                }
            }

            /// <summary>
            /// The VIPCount0 item info.
            /// </summary>
            [RepositoryItemInfo("0949d5cc-0326-4e1f-9cf7-1a5590cae2dc")]
            public virtual RepoItemInfo VIPCount0Info
            {
                get
                {
                    return _vipcount0Info;
                }
            }

            /// <summary>
            /// The VIPDatabase item.
            /// </summary>
            [RepositoryItem("c4e0c7f1-91ec-4b46-8fdd-a59558719532")]
            public virtual Ranorex.TitleBar VIPDatabase
            {
                get
                {
                    return _vipdatabaseInfo.CreateAdapter<Ranorex.TitleBar>(true);
                }
            }

            /// <summary>
            /// The VIPDatabase item info.
            /// </summary>
            [RepositoryItemInfo("c4e0c7f1-91ec-4b46-8fdd-a59558719532")]
            public virtual RepoItemInfo VIPDatabaseInfo
            {
                get
                {
                    return _vipdatabaseInfo;
                }
            }
        }

    }
#pragma warning restore 0436
}
